services:
  backend:
    build:
      context: ./backend
    container_name: petmon_backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: petmon
      DB_USER: root
      DB_PASSWORD: srv123!
      JWT_SECRET: pEtMon_rEhAN_esG_PLatFoRM_Authorization_Secret_KEY
      SERIAL_PORT: /dev/ttyUSB0
      ENABLE_HARDWARE: ${ENABLE_HARDWARE:-true}
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    restart: unless-stopped
    # USB 디바이스는 docker-compose.hardware.yaml에서만 마운트

  mysql:
    image: mysql:8.0
    container_name: petmon_mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: srv123!
      MYSQL_DATABASE: petmon
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=caching_sha2_password --init-connect="SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: petmon_frontend
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BACKEND_URL: http://localhost:3001
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
