services:
  backend:
    build:
      context: ./backend
    container_name: petmon_backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: petmon
      DB_USER: root
      DB_PASSWORD: srv123!
      JWT_SECRET: pEtMon_rEhAN_esG_PLatFoRM_Authorization_Secret_KEY
      SERIAL_PORT: /dev/ttyUSB0
    volumes:
      - ./backend:/app
      - /app/node_modules
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    ports:
      - "3001:3001"
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: petmon_mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: srv123!
      MYSQL_DATABASE: petmon
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: petmon_frontend
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BACKEND_URL: http://backend:3001
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
