version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rehan_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rehan_esg_platform
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      interval: 30s
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: rehan_backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: rehan_esg_platform
      DB_USER: app_user
      DB_PASSWORD: app_password
      NODE_ENV: development
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: rehan_frontend
    depends_on:
      - backend
    ports:
      - "80:80" # 실제 배포 서버에서는 3000:80 내부포트:외부포트
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://backend:3001
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  default:
    name: rehan_network
