services:
  backend:
    build: ./backend
    container_name: rehan_backend
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: petmon
      DB_USER: root
      DB_PASSWORD: srv123!
      NODE_ENV: development
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: rehan_mysql
    environment:
      MYSQL_ROOT_PASSWORD: srv123!
      MYSQL_DATABASE: petmon
      MYSQL_USER: root
      MYSQL_PASSWORD: srv123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: rehan_frontend
    depends_on:
      - backend
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://backend:3001
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  default:
    name: rehan_network
