services:
  backend:
    build:
      context: ./backend
      network: host
    container_name: petmon_backend
    network_mode: host
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: petmon
      DB_USER: root
      DB_PASSWORD: srv123!
      NODE_ENV: development
      SERIAL_PORT: /dev/ttyUSB0
    volumes:
      - ./backend:/app
      - /app/node_modules
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: petmon_mysql
    network_mode: host
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: srv123!
      MYSQL_DATABASE: petmon
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      network: host
    container_name: petmon_frontend
    network_mode: host
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      BACKEND_URL: http://localhost:3001
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
