services:
  backend:
    build:
      context: ./backend
      network: host
    container_name: rehan_backend
    network_mode: host
    depends_on:
      - mysql
    environment:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: petmon
      DB_USER: root
      DB_PASSWORD: srv123!
      NODE_ENV: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: rehan_mysql
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: srv123!
      MYSQL_DATABASE: petmon
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      network: host
    container_name: rehan_frontend
    network_mode: host
    depends_on:
      - backend
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://localhost:3001
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
