services:
  backend:
    build: ./backend
    container_name: rehan_backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: petmon
      DB_USER: root
      DB_PASSWORD: srv123!
      NODE_ENV: development
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: rehan_frontend
    depends_on:
      - backend
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://backend:3001
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  default:
    name: rehan_network
