-- 기존 테이블이 있다면 삭제
DROP TABLE IF EXISTS TBL_ERROR_REPORT;

CREATE TABLE TBL_ERROR_REPORT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    phone_number VARCHAR(11) NOT NULL,
    error_content VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);